name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: basic
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.basic.svg
          config_timezone: Asia/Shanghai
          user: xctan
          base: header, repositories
      - name: language
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.language.svg
          user: xctan
          base: ""
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_analysis_timeout: 40
          plugin_languages_colors: github
          plugin_languages_limit: 7
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          commits_authoring: axunlei@gmail.com, xctan@cirno.icu, sterprim@outlook.com
